#ifndef MOVES_DATA_HPP
#define MOVES_DATA_HPP

#include "Cube.hpp"

const FaceSlice FACE_CYCLES[6][4] = 
{
	//FACE_F
	{
		{FACE_U, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}},
		{FACE_L, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_D, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}},
		{FACE_R, {POS_TOP_LEFT, POS_LEFT, POS_BOT_LEFT}}
	},

	//FACE_B
	{
		{FACE_U, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}},
		{FACE_R, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_D, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}},
		{FACE_L, {POS_BOT_LEFT, POS_LEFT, POS_TOP_LEFT}}		
	},

	//FACE_U
	{
		{FACE_B, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}},
		{FACE_L, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}},
		{FACE_F, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}},
		{FACE_R, {POS_TOP_RIGHT, POS_TOP, POS_TOP_LEFT}}
		
	},

	//FACE_D
	{
		{FACE_F, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}},
		{FACE_L, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}},
		{FACE_B, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}},
		{FACE_R, {POS_BOT_LEFT, POS_BOT, POS_BOT_RIGHT}}
	},

	//FACE_L
	{
		{FACE_U, {POS_TOP_LEFT, POS_LEFT, POS_BOT_LEFT}},
		{FACE_B, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_D, {POS_TOP_LEFT, POS_LEFT, POS_BOT_LEFT}},
		{FACE_F, {POS_TOP_LEFT, POS_LEFT, POS_BOT_LEFT}}
	},

	//FACE_R
	{
		{FACE_U, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_F, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_D, {POS_BOT_RIGHT, POS_RIGHT, POS_TOP_RIGHT}},
		{FACE_B, {POS_TOP_LEFT, POS_LEFT, POS_BOT_LEFT}}
	}
};

const int ROTATION_CW[8] = {6, 3, 0, 7, 1, 8, 5, 2};

#endif